language:
  - python
  - node_js
python: "2.7"
node_js: "0.10"
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
    apt:
        packages:
            - language-pack-en
install:
    - make test.acceptance
    - pip install coveralls
script:
    - make static -e DJANGO_SETTINGS_MODULE="analytics_dashboard.settings.test"
    - make validate
    - make generate_fake_translations
    - make accept
    - make a11y
branches:
    only:
      - master
after_success:
    - coveralls
    - bash ./scripts/build-stats-to-datadog.sh
deploy:
    - provider: s3
      access_key_id: $S3_ACCESS_KEY_ID
      secret_access_key: $S3_SECRET_ACCESS_KEY
      bucket: $S3_BUCKET
      skip_cleanup: true
      local_dir: $TRAVIS_BUILD_DIR/build-metrics
      upload_dir: edx-analytics-dashboard/master
      acl: public_read
      on:
        branch: master
